### ISSUE TITLE
Request to upload models to OSF.io due to Google Drive access limitations

### ISSUE THREAD

**Issue by vmikk** [ml4bio/USPNet#1]
Hello!

I am writing to bring to your attention an issue that I, and potentially other users, have encountered while trying to access the trained predictive model files associated with `USPNet`. Currently, these files are hosted on Google Drive. Unfortunately, when attempting to download the data, Google Drive displays the following error message: `Too many users have viewed or downloaded this file recently. Please try accessing the file again later`. This issue hinders access to the essential components of the project.

As a solution, I kindly request that the trained predictive model files be uploaded to **OSF.io**, where other project data are currently hosted (https://osf.io/nh3cf/).

Thank you for considering this request.

**Comment by JunboShen** [comment]
Hello,

Thank you for pointing out the Google Drive download limitation. We've taken your feedback into account and have uploaded the trained predictive model files to OSF.io. We appreciate your patience and support.
