### ISSUE TITLE
Can I run these .py files on  CPU?

### ISSUE THREAD

**Issue by yangfa-zhang** [ml4bio/USPNet#2]

**Comment by JunboShen** [comment]
Current .py files in the repository cannot directly run on CPU. 
You can try the following: Change "device = torch.device("cuda:0")" to "device = torch.device("cpu")".
Replace all ".cuda()" calls with ".to(device)", where "device" is the CPU device you've defined.
Thank you!

**Comment by yangfa-zhang** [comment]
@JunboShen thanks!
